version: '3'
services:
  db:
    image: kartoza/postgis
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dating
    container_name: dating_bot_db
