version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6378:6379"
    container_name: dating_bot_redis
    restart: unless-stopped
    networks:
      - dating-bot-network

  db:
    image: kartoza/postgis:14-3.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_MULTIPLE_DATABASES: postgres
    container_name: dating_bot_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./config/RU.txt:/RU.txt
    restart: unless-stopped
    networks:
      - dating-bot-network


networks:
  dating-bot-network:
    driver: bridge